plugins = []
headers = []
redirects = []

[database]

  [database.migrations]
  path = "/opt/build/repo/netlify/database/migrations"

[build]
publish = "/opt/build/repo/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[functions]

  [functions."*"]